version: '3'
services:
  postgresql:
    image: "postgres:latest"
    ports:
     - "5433:5432"
    environment:
      - POSTGRES_DATABASE=coffeerecipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres