version: '3.8'

networks:
  network:
    name: network
    
services:
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffeerecipes
    ports:
      - "5432:5432"
    networks:
      - network