version: '3.9'

networks:
  network:
    name: network
    
services:
  api:
    image: coffeerecipeapi
    build:
      context: ./Api
      dockerfile: ./Dockerfile
    env_file:
      - Api/file.env
    depends_on:
      - db
    container_name: utm
    environment:
        ConnectionStrings__Marten: Host=db;Database=coffeerecipes;Username=postgres;Password=postgres;
        ASPNETCORE_Kestrel__Certificates__Default__Password: 2137
        ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
        HTTP_PORTS: 80
        HTTPS_PORT: 443
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - network
    volumes:
      - ./https:/https:ro
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffeerecipes
    ports:
      - "5432:5432"
    networks:
      - network