@CoffeeRecipes_HostAddress = http://localhost:5235
### Get Roasters
GET {{CoffeeRecipes_HostAddress}}/Roasters//
Accept: application/json

### Get Cities by Province
GET {{CoffeeRecipes_HostAddress}}/Map/City/
Accept: application/json

### Get Provinces
GET {{CoffeeRecipes_HostAddress}}/Map/Province
Accept: application/json