version: '3.8'

networks:
  network:
    name: network

services:
  web:
    container_name: proxy
    image: nginx:alpine
    restart: always
    ports:
      #        - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/var/www/html
      - ./nginx:/etc/nginx
      - ./certbot:/etc/letsencrypt
    networks:
      - network
    depends_on:
      - api
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffeerecipes
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - network
  api:
    container_name: api
    image: aluspl/coffeerecipesapi:develop
    ports:
      - "80:80"
    environment:
      ConnectionStrings__Marten: Host=db;Database=coffeerecipes;Username=postgres;Password=postgres;
      ASPNETCORE_URLS: "http://*:80"
    networks:
      - network
    depends_on:
      - db
    volumes:
      - ./https:/https:ro
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - ./frontend:/var/www/html
#      - ./certbot:/etc/letsencrypt
#    depends_on:
#      - web
#    command: certonly --webroot --webroot-path=/var/www/html --email szymon@lifelike.pl --agree-tos --no-eff-email --staging -d dev-recipes.lifelike.pl -d www.dev-recipes.lifelike.pl