version: '3.9'

networks:
  network:
    name: network

services:
  web:
    container_name: proxy
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/www:/var/www/html
      - ./certbot/www:/var/www/certbot/:ro
      - ./nginx-cert:/etc/nginx
      - ./certbot:/etc/letsencrypt
    networks:
      - network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./certbot/www/:/var/www/html/:rw
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email szymon@lifelike.pl --agree-tos --no-eff-email -d dev-recipes.lifelike.pl -d www.dev-recipes.lifelike.pl