apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coffeerecipes-api-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: {{ .Values.tls.issuerName }}
spec:
  tls:
    - hosts:
        {{- range .Values.hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.hosts | first }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.port }}
