apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffeerecipes-api.fullname" . }}
  labels:
    app: {{ include "coffeerecipes-api.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "coffeerecipes-api.name" . }}
