name: Build Docker Image

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build Api --file Dockerfile --tag lifelikepl\coffeerecipes-api:$(date +%s)